name: Auto-approve Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewer
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Automatically approved by workflow.'
            });
            console.log(response);
